-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.endereco
(
    idendereco bigint NOT NULL DEFAULT nextval('endereco_idendereco_seq'::regclass),
    idpessoa bigint NOT NULL,
    dscep character varying(15) COLLATE pg_catalog."default",
    dsnumero integer,
    CONSTRAINT endereco_pk PRIMARY KEY (idendereco)
);

CREATE TABLE IF NOT EXISTS public.endereco_integracao
(
    idendereco bigint NOT NULL,
    dsuf character varying(50) COLLATE pg_catalog."default",
    nmcidade character varying(100) COLLATE pg_catalog."default",
    nmbairro character varying(50) COLLATE pg_catalog."default",
    nmlogradouro character varying(100) COLLATE pg_catalog."default",
    dscomplemento character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT enderecointegracao_pk PRIMARY KEY (idendereco)
);

CREATE TABLE IF NOT EXISTS public.pessoa
(
    idpessoa bigint NOT NULL DEFAULT nextval('pessoa_idpessoa_seq'::regclass),
    dsdocumento character varying(20) COLLATE pg_catalog."default" NOT NULL,
    nmprimeiro character varying(100) COLLATE pg_catalog."default" NOT NULL,
    nmsegundo character varying(100) COLLATE pg_catalog."default" NOT NULL,
    dtregistro date,
    flnatureza sexo_full COLLATE pg_catalog."default",
    CONSTRAINT pessoa_pk PRIMARY KEY (idpessoa)
);

ALTER TABLE IF EXISTS public.endereco
    ADD CONSTRAINT endereco_fk_pessoa FOREIGN KEY (idpessoa)
    REFERENCES public.pessoa (idpessoa) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS endereco_idpessoa
    ON public.endereco(idpessoa);


ALTER TABLE IF EXISTS public.endereco_integracao
    ADD CONSTRAINT enderecointegracao_fk_endereco FOREIGN KEY (idendereco)
    REFERENCES public.endereco (idendereco) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS enderecointegracao_pk
    ON public.endereco_integracao(idendereco);

END;